/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tibiarobot;

import javax.swing.JOptionPane;

/**
 *
 * @author vfrodrigues
 */
public class TibiaRobotF extends javax.swing.JFrame {
    
    private Thread thtibia;
    private TibiaRobot tibia;

    /**
     * Creates new form TibiaRobotF
     */
    public TibiaRobotF() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbIniciar = new javax.swing.JButton();
        jbParar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtfTempoEspera = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfChar1Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbChar1Ativo = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jcbChar1F1 = new javax.swing.JCheckBox();
        jcbChar1F2 = new javax.swing.JCheckBox();
        jcbChar1F3 = new javax.swing.JCheckBox();
        jcbChar1F4 = new javax.swing.JCheckBox();
        jcbChar1F5 = new javax.swing.JCheckBox();
        jcbChar1F6 = new javax.swing.JCheckBox();
        jcbChar1F7 = new javax.swing.JCheckBox();
        jcbChar1F8 = new javax.swing.JCheckBox();
        jcbChar1F9 = new javax.swing.JCheckBox();
        jcbChar1F10 = new javax.swing.JCheckBox();
        jcbChar1F11 = new javax.swing.JCheckBox();
        jcbChar1F12 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtfChar2Name = new javax.swing.JTextField();
        jcbChar2Ativo = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jcbChar2F1 = new javax.swing.JCheckBox();
        jcbChar2F2 = new javax.swing.JCheckBox();
        jcbChar2F3 = new javax.swing.JCheckBox();
        jcbChar2F4 = new javax.swing.JCheckBox();
        jcbChar2F5 = new javax.swing.JCheckBox();
        jcbChar2F6 = new javax.swing.JCheckBox();
        jcbChar2F7 = new javax.swing.JCheckBox();
        jcbChar2F8 = new javax.swing.JCheckBox();
        jcbChar2F9 = new javax.swing.JCheckBox();
        jcbChar2F10 = new javax.swing.JCheckBox();
        jcbChar2F11 = new javax.swing.JCheckBox();
        jcbChar2F12 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jcbChar3Ativo = new javax.swing.JCheckBox();
        jtfChar3Name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jcbChar3F1 = new javax.swing.JCheckBox();
        jcbChar3F2 = new javax.swing.JCheckBox();
        jcbChar3F3 = new javax.swing.JCheckBox();
        jcbChar3F4 = new javax.swing.JCheckBox();
        jcbChar3F5 = new javax.swing.JCheckBox();
        jcbChar3F6 = new javax.swing.JCheckBox();
        jcbChar3F7 = new javax.swing.JCheckBox();
        jcbChar3F8 = new javax.swing.JCheckBox();
        jcbChar3F9 = new javax.swing.JCheckBox();
        jcbChar3F10 = new javax.swing.JCheckBox();
        jcbChar3F11 = new javax.swing.JCheckBox();
        jcbChar3F12 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfChar4Name = new javax.swing.JTextField();
        jcbChar4Ativo = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jcbChar4F1 = new javax.swing.JCheckBox();
        jcbChar4F2 = new javax.swing.JCheckBox();
        jcbChar4F3 = new javax.swing.JCheckBox();
        jcbChar4F4 = new javax.swing.JCheckBox();
        jcbChar4F5 = new javax.swing.JCheckBox();
        jcbChar4F6 = new javax.swing.JCheckBox();
        jcbChar4F7 = new javax.swing.JCheckBox();
        jcbChar4F8 = new javax.swing.JCheckBox();
        jcbChar4F9 = new javax.swing.JCheckBox();
        jcbChar4F10 = new javax.swing.JCheckBox();
        jcbChar4F11 = new javax.swing.JCheckBox();
        jcbChar4F12 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TibiaRobot by @viniciusfacco");

        jbIniciar.setText("Iniciar");
        jbIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarActionPerformed(evt);
            }
        });

        jbParar.setText("Parar");
        jbParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPararActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel13.setText("Tempo de Espera");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfTempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Parâmetros", jPanel1);

        jLabel1.setText("Nome");

        jcbChar1Ativo.setText("Ativar");

        jLabel14.setText("Hotkeys");

        jcbChar1F1.setText("F1");

        jcbChar1F2.setText("F2");

        jcbChar1F3.setText("F3");

        jcbChar1F4.setText("F4");

        jcbChar1F5.setText("F5");

        jcbChar1F6.setText("F6");

        jcbChar1F7.setText("F7");

        jcbChar1F8.setText("F8");

        jcbChar1F9.setText("F9");

        jcbChar1F10.setText("F10");

        jcbChar1F11.setText("F11");

        jcbChar1F12.setText("F12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfChar1Name, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbChar1Ativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcbChar1F2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar1F4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar1F6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar1F8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar1F10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcbChar1F1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar1F3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar1F5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar1F7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar1F9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbChar1F11)
                            .addComponent(jcbChar1F12))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfChar1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jcbChar1Ativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbChar1F1)
                        .addComponent(jcbChar1F3)
                        .addComponent(jcbChar1F5)
                        .addComponent(jcbChar1F7)
                        .addComponent(jcbChar1F9)
                        .addComponent(jcbChar1F11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbChar1F2)
                    .addComponent(jcbChar1F4)
                    .addComponent(jcbChar1F6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbChar1F8)
                    .addComponent(jcbChar1F10)
                    .addComponent(jcbChar1F12))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Char 1", jPanel2);

        jLabel7.setText("Nome");

        jcbChar2Ativo.setText("Ativar");

        jLabel3.setText("Hotkeys");

        jcbChar2F1.setText("F1");

        jcbChar2F2.setText("F2");

        jcbChar2F3.setText("F3");

        jcbChar2F4.setText("F4");

        jcbChar2F5.setText("F5");

        jcbChar2F6.setText("F6");

        jcbChar2F7.setText("F7");

        jcbChar2F8.setText("F8");

        jcbChar2F9.setText("F9");

        jcbChar2F10.setText("F10");

        jcbChar2F11.setText("F11");

        jcbChar2F12.setText("F12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfChar2Name, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbChar2Ativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jcbChar2F1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar2F3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar2F5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar2F7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar2F9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jcbChar2F2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar2F4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar2F6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar2F8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar2F10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbChar2F11)
                            .addComponent(jcbChar2F12))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfChar2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcbChar2Ativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbChar2F1)
                        .addComponent(jcbChar2F3)
                        .addComponent(jcbChar2F5)
                        .addComponent(jcbChar2F7)
                        .addComponent(jcbChar2F9)
                        .addComponent(jcbChar2F11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbChar2F2)
                    .addComponent(jcbChar2F4)
                    .addComponent(jcbChar2F6)
                    .addComponent(jcbChar2F8)
                    .addComponent(jcbChar2F10)
                    .addComponent(jcbChar2F12))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Char 2", jPanel3);

        jLabel10.setText("Nome");

        jcbChar3Ativo.setText("Ativar");

        jLabel8.setText("Hotkeys");

        jcbChar3F1.setText("F1");

        jcbChar3F2.setText("F2");

        jcbChar3F3.setText("F3");

        jcbChar3F4.setText("F4");

        jcbChar3F5.setText("F5");

        jcbChar3F6.setText("F6");

        jcbChar3F7.setText("F7");

        jcbChar3F8.setText("F8");

        jcbChar3F9.setText("F9");

        jcbChar3F10.setText("F10");

        jcbChar3F11.setText("F11");

        jcbChar3F12.setText("F12");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfChar3Name, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbChar3Ativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jcbChar3F2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar3F4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar3F6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar3F8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar3F10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jcbChar3F1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar3F3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar3F5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar3F7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar3F9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbChar3F11)
                            .addComponent(jcbChar3F12))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfChar3Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jcbChar3Ativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbChar3F1)
                        .addComponent(jcbChar3F3)
                        .addComponent(jcbChar3F5)
                        .addComponent(jcbChar3F7)
                        .addComponent(jcbChar3F9)
                        .addComponent(jcbChar3F11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbChar3F2)
                    .addComponent(jcbChar3F4)
                    .addComponent(jcbChar3F6)
                    .addComponent(jcbChar3F8)
                    .addComponent(jcbChar3F10)
                    .addComponent(jcbChar3F12))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Char 3", jPanel4);

        jLabel4.setText("Nome");

        jcbChar4Ativo.setText("Ativar");

        jLabel9.setText("Hotkeys");

        jcbChar4F1.setText("F1");

        jcbChar4F2.setText("F2");

        jcbChar4F3.setText("F3");

        jcbChar4F4.setText("F4");

        jcbChar4F5.setText("F5");

        jcbChar4F6.setText("F6");

        jcbChar4F7.setText("F7");

        jcbChar4F8.setText("F8");

        jcbChar4F9.setText("F9");

        jcbChar4F10.setText("F10");

        jcbChar4F11.setText("F11");

        jcbChar4F12.setText("F12");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfChar4Name, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbChar4Ativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jcbChar4F2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar4F4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar4F6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar4F8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar4F10))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jcbChar4F1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar4F3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar4F5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar4F7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChar4F9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbChar4F11)
                            .addComponent(jcbChar4F12))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfChar4Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jcbChar4Ativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbChar4F1)
                        .addComponent(jcbChar4F3)
                        .addComponent(jcbChar4F5)
                        .addComponent(jcbChar4F7)
                        .addComponent(jcbChar4F9)
                        .addComponent(jcbChar4F11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbChar4F2)
                    .addComponent(jcbChar4F4)
                    .addComponent(jcbChar4F6)
                    .addComponent(jcbChar4F8)
                    .addComponent(jcbChar4F10)
                    .addComponent(jcbChar4F12))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Char 4", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbIniciar)
                    .addComponent(jbParar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarActionPerformed
        if (!jtfTempoEspera.getText().equals("")){
            Char ch;
            jTextArea1.append("Sistema iniciado.\n");
            jTextArea1.setCaretPosition(jTextArea1.getText().length());
            jbIniciar.setEnabled(false);
            tibia = null;
            tibia = new TibiaRobot(this.jTextArea1, Integer.parseInt(jtfTempoEspera.getText()));
            if(jcbChar1Ativo.isSelected()){
                ch = new Char(jcbChar1Ativo.isSelected(), jtfChar1Name.getText());
                if(jcbChar1F1.isSelected()){ch.addHotKey(jcbChar1F1.getText());}
                if(jcbChar1F2.isSelected()){ch.addHotKey(jcbChar1F2.getText());}
                if(jcbChar1F3.isSelected()){ch.addHotKey(jcbChar1F3.getText());}
                if(jcbChar1F4.isSelected()){ch.addHotKey(jcbChar1F4.getText());}
                if(jcbChar1F5.isSelected()){ch.addHotKey(jcbChar1F5.getText());}
                if(jcbChar1F6.isSelected()){ch.addHotKey(jcbChar1F6.getText());}
                if(jcbChar1F7.isSelected()){ch.addHotKey(jcbChar1F7.getText());}
                if(jcbChar1F8.isSelected()){ch.addHotKey(jcbChar1F8.getText());}
                if(jcbChar1F9.isSelected()){ch.addHotKey(jcbChar1F9.getText());}
                if(jcbChar1F10.isSelected()){ch.addHotKey(jcbChar1F10.getText());}
                if(jcbChar1F11.isSelected()){ch.addHotKey(jcbChar1F11.getText());}
                if(jcbChar1F12.isSelected()){ch.addHotKey(jcbChar1F12.getText());}
                tibia.addChar(ch);
            }
            if(jcbChar2Ativo.isSelected()){
                ch = new Char(jcbChar2Ativo.isSelected(), jtfChar2Name.getText());
                if(jcbChar2F1.isSelected()){ch.addHotKey(jcbChar2F1.getText());}
                if(jcbChar2F2.isSelected()){ch.addHotKey(jcbChar2F2.getText());}
                if(jcbChar2F3.isSelected()){ch.addHotKey(jcbChar2F3.getText());}
                if(jcbChar2F4.isSelected()){ch.addHotKey(jcbChar2F4.getText());}
                if(jcbChar2F5.isSelected()){ch.addHotKey(jcbChar2F5.getText());}
                if(jcbChar2F6.isSelected()){ch.addHotKey(jcbChar2F6.getText());}
                if(jcbChar2F7.isSelected()){ch.addHotKey(jcbChar2F7.getText());}
                if(jcbChar2F8.isSelected()){ch.addHotKey(jcbChar2F8.getText());}
                if(jcbChar2F9.isSelected()){ch.addHotKey(jcbChar2F9.getText());}
                if(jcbChar2F10.isSelected()){ch.addHotKey(jcbChar2F10.getText());}
                if(jcbChar2F11.isSelected()){ch.addHotKey(jcbChar2F11.getText());}
                if(jcbChar2F12.isSelected()){ch.addHotKey(jcbChar2F12.getText());}
                tibia.addChar(ch);
            }
            if(jcbChar3Ativo.isSelected()){
                ch = new Char(jcbChar3Ativo.isSelected(), jtfChar3Name.getText());
                if(jcbChar3F1.isSelected()){ch.addHotKey(jcbChar3F1.getText());}
                if(jcbChar3F2.isSelected()){ch.addHotKey(jcbChar3F2.getText());}
                if(jcbChar3F3.isSelected()){ch.addHotKey(jcbChar3F3.getText());}
                if(jcbChar3F4.isSelected()){ch.addHotKey(jcbChar3F4.getText());}
                if(jcbChar3F5.isSelected()){ch.addHotKey(jcbChar3F5.getText());}
                if(jcbChar3F6.isSelected()){ch.addHotKey(jcbChar3F6.getText());}
                if(jcbChar3F7.isSelected()){ch.addHotKey(jcbChar3F7.getText());}
                if(jcbChar3F8.isSelected()){ch.addHotKey(jcbChar3F8.getText());}
                if(jcbChar3F9.isSelected()){ch.addHotKey(jcbChar3F9.getText());}
                if(jcbChar3F10.isSelected()){ch.addHotKey(jcbChar3F10.getText());}
                if(jcbChar3F11.isSelected()){ch.addHotKey(jcbChar3F11.getText());}
                if(jcbChar3F12.isSelected()){ch.addHotKey(jcbChar3F12.getText());}
                tibia.addChar(ch);
            }
            if(jcbChar4Ativo.isSelected()){
                ch = new Char(jcbChar4Ativo.isSelected(), jtfChar4Name.getText());
                if(jcbChar4F1.isSelected()){ch.addHotKey(jcbChar4F1.getText());}
                if(jcbChar4F2.isSelected()){ch.addHotKey(jcbChar4F2.getText());}
                if(jcbChar4F3.isSelected()){ch.addHotKey(jcbChar4F3.getText());}
                if(jcbChar4F4.isSelected()){ch.addHotKey(jcbChar4F4.getText());}
                if(jcbChar4F5.isSelected()){ch.addHotKey(jcbChar4F5.getText());}
                if(jcbChar4F6.isSelected()){ch.addHotKey(jcbChar4F6.getText());}
                if(jcbChar4F7.isSelected()){ch.addHotKey(jcbChar4F7.getText());}
                if(jcbChar4F8.isSelected()){ch.addHotKey(jcbChar4F8.getText());}
                if(jcbChar4F9.isSelected()){ch.addHotKey(jcbChar4F9.getText());}
                if(jcbChar4F10.isSelected()){ch.addHotKey(jcbChar4F10.getText());}
                if(jcbChar4F11.isSelected()){ch.addHotKey(jcbChar4F11.getText());}
                if(jcbChar4F12.isSelected()){ch.addHotKey(jcbChar4F12.getText());}
                tibia.addChar(ch);
            }
            thtibia = new Thread(tibia);
            thtibia.start();
        } else {
            JOptionPane.showMessageDialog(null, "Tempo de espera inválido.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jbIniciarActionPerformed

    private void jbPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPararActionPerformed
        this.jbIniciar.setEnabled(true);
        tibia.parar();
        jTextArea1.append("Sistema parado.\n");
        jTextArea1.setCaretPosition(jTextArea1.getText().length());
    }//GEN-LAST:event_jbPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TibiaRobotF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TibiaRobotF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TibiaRobotF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TibiaRobotF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TibiaRobotF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbIniciar;
    private javax.swing.JButton jbParar;
    private javax.swing.JCheckBox jcbChar1Ativo;
    private javax.swing.JCheckBox jcbChar1F1;
    private javax.swing.JCheckBox jcbChar1F10;
    private javax.swing.JCheckBox jcbChar1F11;
    private javax.swing.JCheckBox jcbChar1F12;
    private javax.swing.JCheckBox jcbChar1F2;
    private javax.swing.JCheckBox jcbChar1F3;
    private javax.swing.JCheckBox jcbChar1F4;
    private javax.swing.JCheckBox jcbChar1F5;
    private javax.swing.JCheckBox jcbChar1F6;
    private javax.swing.JCheckBox jcbChar1F7;
    private javax.swing.JCheckBox jcbChar1F8;
    private javax.swing.JCheckBox jcbChar1F9;
    private javax.swing.JCheckBox jcbChar2Ativo;
    private javax.swing.JCheckBox jcbChar2F1;
    private javax.swing.JCheckBox jcbChar2F10;
    private javax.swing.JCheckBox jcbChar2F11;
    private javax.swing.JCheckBox jcbChar2F12;
    private javax.swing.JCheckBox jcbChar2F2;
    private javax.swing.JCheckBox jcbChar2F3;
    private javax.swing.JCheckBox jcbChar2F4;
    private javax.swing.JCheckBox jcbChar2F5;
    private javax.swing.JCheckBox jcbChar2F6;
    private javax.swing.JCheckBox jcbChar2F7;
    private javax.swing.JCheckBox jcbChar2F8;
    private javax.swing.JCheckBox jcbChar2F9;
    private javax.swing.JCheckBox jcbChar3Ativo;
    private javax.swing.JCheckBox jcbChar3F1;
    private javax.swing.JCheckBox jcbChar3F10;
    private javax.swing.JCheckBox jcbChar3F11;
    private javax.swing.JCheckBox jcbChar3F12;
    private javax.swing.JCheckBox jcbChar3F2;
    private javax.swing.JCheckBox jcbChar3F3;
    private javax.swing.JCheckBox jcbChar3F4;
    private javax.swing.JCheckBox jcbChar3F5;
    private javax.swing.JCheckBox jcbChar3F6;
    private javax.swing.JCheckBox jcbChar3F7;
    private javax.swing.JCheckBox jcbChar3F8;
    private javax.swing.JCheckBox jcbChar3F9;
    private javax.swing.JCheckBox jcbChar4Ativo;
    private javax.swing.JCheckBox jcbChar4F1;
    private javax.swing.JCheckBox jcbChar4F10;
    private javax.swing.JCheckBox jcbChar4F11;
    private javax.swing.JCheckBox jcbChar4F12;
    private javax.swing.JCheckBox jcbChar4F2;
    private javax.swing.JCheckBox jcbChar4F3;
    private javax.swing.JCheckBox jcbChar4F4;
    private javax.swing.JCheckBox jcbChar4F5;
    private javax.swing.JCheckBox jcbChar4F6;
    private javax.swing.JCheckBox jcbChar4F7;
    private javax.swing.JCheckBox jcbChar4F8;
    private javax.swing.JCheckBox jcbChar4F9;
    private javax.swing.JTextField jtfChar1Name;
    private javax.swing.JTextField jtfChar2Name;
    private javax.swing.JTextField jtfChar3Name;
    private javax.swing.JTextField jtfChar4Name;
    private javax.swing.JTextField jtfTempoEspera;
    // End of variables declaration//GEN-END:variables
}
